volumes:
  db-data:

networks:
  gateway:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: kvdomingo/squad-awards-api:latest
    env_file: .env
    depends_on:
      - postgres

  proxy:
    image: bitnami/nginx:1.21.6
    environment:
      NGINX_HTTP_PORT_NUMBER: 8000
    volumes:
      - ./proxy/prod:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.squad-awards.rule=Host(`squad-awards.localhost`)"
      - "traefik.http.routers.squad-awards.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.squad-awards.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - default
      - gateway
    depends_on:
      - api

  postgres:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - db-data:/bitnami/postgresql
