version: '3'

env:
  ENV: dev
  NAME: squad-awards-{{.ENV}}

dotenv:
  - .env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml up -d --build --remove-orphans {{.CLI_ARGS}}
      - task logs

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml exec -- proxy nginx -s reload

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml logs --follow {{.CLI_ARGS}}

  shutdown:
    desc: Stop all containers
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose -p {{.NAME}} -f docker-compose.{{.ENV}}.yml down -v --remove-orphans {{.CLI_ARGS}}
