# Generated by Django 4.1.4 on 2022-12-11 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("discord_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("avatar", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=32)),
                ("discriminator", models.CharField(max_length=4)),
            ],
            options={
                "ordering": ["username"],
                "unique_together": {("username", "discriminator")},
            },
        ),
    ]
