# Generated by Django 4.1.4 on 2022-12-12 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BFSA", "Best Female Solo Artist"),
                            ("BMSA", "Best Male Solo Artist"),
                            ("BFG", "Best Female Group"),
                            ("BMG", "Best Male Group"),
                            ("MVOTY", "Music Video of the Year"),
                            ("ROTY", "Rookie of the Year"),
                            ("AOTY", "Album of the Year"),
                            ("SOTY", "Song of the Year"),
                            ("BOTY", "B-Side of the Year"),
                            ("SADGE", "Sadge of the Year"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["user", "answer__category"]},
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="api.discorduser"),
        ),
        migrations.RemoveField(
            model_name="answer",
            name="category",
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.awardchoice"),
        ),
    ]
