# Generated by Django 4.1.4 on 2022-12-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_awardchoice_alter_answer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardchoice",
            name="image",
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
