# Generated by Django 4.1.4 on 2022-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_awardchoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="answers",
            field=models.JSONField(default="{}"),
            preserve_default=False,
        ),
    ]
